DROP TABLE IF EXISTS `{__TABLEPREX__}{__TABLE_NAME__}`;
CREATE TABLE `{__TABLEPREX__}{__TABLE_NAME__}` (
  `id`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT ,
  `title` char(255) NOT NULL DEFAULT '',
  `create_time`  int(10) UNSIGNED NOT NULL DEFAULT 0 ,
  `update_time`  int(10) UNSIGNED NOT NULL DEFAULT 0 ,
  PRIMARY KEY (`id`)
)
ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci COMMENT='{__TABLE_DESCRIPTION__}' AUTO_INCREMENT=1 CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0